Fix typo
CarlosUJED/hyperblog pull request #1
Opened 2019-10-11 15:03 UTC by CarlosUJED

No debimos pasar este error a master

2019-10-11 15:08 UTC, gitmrusuario0001 requested changes
Pues en vez de tildes directas es es necesario usar entidades HTML

2019-10-11 15:08 UTC, gitmrusuario0001 commented on blogpost.html
En vez de usar tildes tienes que usar html directos

2019-10-11 15:11 UTC, gitmrusuario0001 requested changes
request changes

2019-10-11 15:13 UTC, gitmrusuario0001 requested changes
tienes que corregir algo

2019-10-12 22:01 UTC, CarlosUJED commented
Cambios hechos hacer el merge

2019-10-12 22:04 UTC, CarlosUJED commented on blogpost.html
> +                    <p>Y este es el p&aacute;rrafo de inicio donde vamos a explicar las cosas incre&iacute;bles que se pueden hacer con ramas</p>
ok start review

2019-10-12 22:06 UTC, gitmrusuario0001 approved these changes
por aqui va la cosa

2019-10-12 22:07 UTC, merged

2019-10-12 22:08 UTC, gitmrusuario0001 reviewed
test review